lunar-linux/moonbase-other

- video/libvdpau/BUILD
I did a fresh install Lunar today. libvdpau failed because libtool 2.4.4 told me to regenerate aclocal.m4.
> libvdpau: fix BUILD with libtool 2.4.4

- web/chromium/BUILD
- web/chromium/DEPENDS
- web/chromium/DETAILS
- web/chromium/PRE_BUILD
- Use bundled version of protobuf or syncing will cause chromium to seg fault
- Added Lunar Linux API keys for the various Google API's chromium can utilize
- Removed unnecessary third part packages cleanup in PRE_BUILD
- Compile and install chromedriver
> chromium: version bumped to 40.0.2214.91

- web/httpd/DETAILS
Note that this rolls back the previous untested version bump from 2.2.27 to 2.4.12.
Please stop bumping the version of httpd from 2.2 to 2.4.  2.2 and 2.4 have incompatible configurations and a bump like that will break everyone's web servers.  Quit doing that.  Make an httpd24 module if you are really intent on using httpd 2.4, or stop bumping the versions of modules you clearly don't use just because a new version has been released.
> httpd: version bump to 2.2.29

- fonts/truetype/DETAILS
- perl/Net-RawSock/DETAILS
- perl/PathTools/DETAILS
- utils/unifdef/DETAILS
I noticed that there are still a few files with text in legacy encodings.
> Various modules DETAILS: Converting iso-8859-1 text to UTF-8.

- i18n/icu4c/DETAILS
The following compiled fine;
yaz
boost
beecrypt
PDFlib-lite
harfbuzz
texlive
R
Qt5
calligra
webkitgtk3
Chromium
openldap
libvisio
You might need more than one pass on a lunar fix depending how your
dependencies get sorted out.
> icu4c: bump to 55.1. You *will* want to do a lunar fix or the like.

- chat/bitlbee/DETAILS
MSN messenger support has been reinstated, for both of the people who
still use that.
> bitlbee: Version bump to 3.4.1

- compilers/gforth/DETAILS
Module untouched since 2008, I bet everyone else forgot that this even existed!
> gforth: version bump to 0.7.3.

- web/firefox-bin/DETAILS
- web/firefox-bin/DETAILS.x86_64
ftp is slow and sometimes hangs for a long time even 100%
> firefox-bin: use http rather than ftp

- x11-wm/i3/DEPENDS
Without libxkbcommon, i3 will fail to compile.
> i3: add missing dependency

- graphics/ufraw/DEPENDS
./configure tries to find lcms2, not lcms version 1 :>
> ufraw: depends lcms2 rather than lcms

- compilers/rustc/DETAILS
I guess there isn't much software in the wild (yet?) written in Rust,
hence the lack of a module for it.
> rustc: The compiler for the Rust programming language

- cd/cdrtools/DEPENDS
- cd/cdrtools/DETAILS
I've added an optional_depends on pulseaudio for the "-echo" feature of cdda2wav which is able to use pulseaudio since 3.02a01.
Thanks
> cdrtools: version bumped to 3.02a01

- web/firefox/DEPENDS
Firefox 39.0.3 needs gst-plugins-base as backend.
> firefox: add missing dependency

- audio/alsa-utils/DEPENDS
fftw3 is needed to build latest alsa-utils.
> alsa-utils: add missing dependency

- web/firefox/DEPENDS
The configure error message:
configure:19613: checking for gconf-2.0 >= 1.2.1 gobject-2.0
configure: error: * * * Could not find gconf-2.0
*** Fix above errors and then restart with\
"/usr/bin/make -f client.mk build"
/usr/src/firefox-43.0.1/client.mk:359: recipe for target 'configure' failed
make[2]: *** [configure] Error 1
make[2]: Leaving directory '/usr/src/firefox-43.0.1'
/usr/src/firefox-43.0.1/client.mk:373: recipe for target '/usr/src/firefox-43.0.1/build-mozilla/Makefile' failed
make[1]: *** [/usr/src/firefox-43.0.1/build-mozilla/Makefile] Error 2
make[1]: Leaving directory '/usr/src/firefox-43.0.1'
client.mk:171: recipe for target 'build' failed
make: *** [build] Error 2
Creating /var/log/lunar/compile/firefox-43.0.1.xz
> firefox: add missing depends

- net/ebtables/BUILD
- net/ebtables/DETAILS
Apparently the latest version of libvirt needs this.  It's a tool
to build firewall rules at the Ethernet bridging level rather than
at the IP level.
> ebtables: new module (actually very old module)

- doc-tools/frescobaldi/BUILD
- doc-tools/frescobaldi/DEPENDS
- doc-tools/frescobaldi/DETAILS
- doc-tools/frescobaldi/PRE_BUILD
This module does not depend on kde anymore
and got completely rewritten since it did.
blocked until the module is actually removed from -kde.
> frescobaldi: moved from -kde

- security/keychain/DETAILS
Supports new ssh features, fixes bugs, according to the changelog.
> keychain: Version bump to 2.8.2

- virtual/libvirt/systemd.d/libvirtd.service
- virtual/libvirt/systemd.d/virtlogd.service
- virtual/libvirt/systemd.d/virtlogd.socket
Libvirtd also requires a log daemon running now.
> libvirtd: Added virtlogd service and socket.

- compilers/go-bootstrap/BUILD
- compilers/go-bootstrap/CONFLICTS
- compilers/go-bootstrap/DEPENDS
- compilers/go-bootstrap/DETAILS
- compilers/go-bootstrap/POST_INSTALL
- compilers/go-bootstrap/PRE_BUILD
- compilers/go/BUILD
- compilers/go/CONFIGURE
- compilers/go/DEPENDS
- compilers/go/DETAILS
- compilers/go/POST_INSTALL
- compilers/go/PRE_BUILD
- compilers/go/profile.d/go.rc
I backported a patch from go1.5 (written in go) to go1.4 (C) that fixes the symbol relocation issues. The patch is part of go-bootstrap. Enjoy!
This closes #540 and closes #567.
> go-bootstrap, go: refactoring

- graphics/ImageMagick/DETAILS
This fixes some really nasty security issues, if you have anyone
in the habit of running ImageMagick from, say, PHP scripts.
> ImageMagick: Version bump to 7.0.1-2.

- sql/mariadb/BUILD
- sql/mariadb/DETAILS
[ 11%] Built target comp_err
Scanning dependencies of target GenError
[ 11%] Generating ../include/mysqld_error.h.tmp
/bin/sh: line 1: 20672 Segmentation fault      (core dumped) ./comp_err --charset=/usr/src/mariadb-10.1.14/sql/share/charsets --out-dir=/usr/src/mariadb-10.1.14/mariadb-oosb/sql/share/ --header_file=/usr/src/mariadb-10.1.14/mariadb-oosb/include/mysqld_error.h.tmp --name_file=/usr/src/mariadb-10.1.14/mariadb-oosb/include/mysqld_ername.h.tmp --state_file=/usr/src/mariadb-10.1.14/mariadb-oosb/include/sql_state.h.tmp --in_file=/usr/src/mariadb-10.1.14/sql/share/errmsg-utf8.txt
make[2]: *** [extra/CMakeFiles/GenError.dir/build.make:62: include/mysqld_error.h.tmp] Error 139
make[1]: *** [CMakeFiles/Makefile2:9445: extra/CMakeFiles/GenError.dir/all] Error 2
make: *** …
> mariadb: Got this error compiling;

- python/Sphinx/DETAILS
Odds are this will need to be done for all of the other python modules
too.
> Sphinx: Changed the url to be https.

- web/fcgi/DETAILS
It's an ancient module and the company that published it went out of
business years ago.
> fcgi: Changed to a working mirror.

- security/clamav/DETAILS
Also, this changes the URL as they seem to have left Sourceforge behind.
> clamav: Version bumped to 0.99.2.

- utils/gdisk/BUILD
- utils/gdisk/DEPENDS
- utils/gdisk/DETAILS
GPT fdisk (consisting of the gdisk, cgdisk, sgdisk, and fixparts programs) is a set of text-mode partitioning tools for Linux, FreeBSD, Mac OS X, and Windows. The gdisk, cgdisk, and sgdisk programs work on Globally Unique Identifier (GUID) Partition Table (GPT) disks, rather than on the more common (through at least early 2013) Master Boot Record (MBR) partition tables. The fixparts program repairs certain types of damage to MBR disks and enables changing partition types from primary to logical and vice-versa.
http://www.rodsbooks.com/gdisk/
https://sourceforge.net/projects/gptfdisk/files/gptfdisk/1.0.1/
> gdisk: new module

- virtual/VirtualBox/VirtualBox
This script is supposed to be used by regular users.
They are usually not privileged to run these commands.
Also if the admin failed to setup the right permissions for these devices,
this is surely not the place to fix this.
> VirtualBox: remove chmod on kernel device from startup script

- games/openttd/DETAILS
changelog @ https://git.openttd.org/?p=tags/1.6.1.git;a=blob_plain;f=changelog.txt;hb=refs/heads/master
> openttd: version bumped to 1.6.1

- graphics/ImageMagick/DETAILS
Also, they deleted the previous version from their downloads directory.
It's really annoying when upstream devs do that, isn't it?
> ImageMagick: Another version bump.

- perl/DBD-SQLite/DETAILS
Annoyingly, the previous version was removed from the source location.
> DBD::SQLite - Version bumped to 1.52.

- graphics/ImageMagick/DETAILS
the archive was not on the mirror sites... I just took the next version
> ImageMagick: version bumped to 6.9.6-8

- i18n/icu-le-hb/BUILD
- i18n/icu-le-hb/DEPENDS
- i18n/icu-le-hb/DETAILS
- i18n/icu4c/DEPENDS
This module is the new support for the ICU layout engine using harfbuzz. Once installed, layoutex/libiculx.so (removed in icu4c-58) will be enabled/included when building icu4c
> New module: icu-le-hb 1.0.3

- audio/pulseaudio/DEPENDS
I want to see if a pulseaudio's configure doesn't fail with this
(later comment edits: catched while doing an update after rtlaneroad's first commit on i3status PR) ... we talked on IRC about it and to let florin have a thought on that
it was closed because I saw "pending" on his PR and thus wanted to let rtlanceroad have another i3status build, but I saw jenkins can trigger more than one at once :P
> pulseaudio: optional udev defaults to n

- graphics/cairo/DEPENDS
then the PDF support will be included in cairo as reclaimed by libreoffice-bin compile error on /usr/include/cairo-pdf.h
> cairo: Added poppler (PDF) dependency required by libreoffice-bin

- graphics/cairo/DEPENDS
When you install librsvg (which is a stricly optional dependency; cairo
builds A-OK without it)), it gives you the option to rebuild cairo with
SVG support anyway.  So let's get rid of it here and lose the circular
dependency.
> cairo: Break the dependency loop.

- graphics/gdk-pixbuf/DEPENDS
Now it depends on shared-mime-info.  And because apparently the
gdk-pixbuf developers haven't been testing how well their package honors
the configuration flags you request, tiff is now a hard dependency
rather than an optional one.
> gdk-pixbuf: Fix up some dependencies.

- libs/libostree/DEPENDS
- libs/libostree/DETAILS
In library form, rather than as an OS management tool, it's also used by
things like "flatpak".
> libostree: New module, for managing binary deployment and upgrades.

- net/samba/CONFIGURE
- net/samba/systemd.d/nmbd.service
- net/samba/systemd.d/samba.service
- net/samba/systemd.d/smbd.service
- net/samba/systemd.d/winbindd.service
Samba has moved its daemons into /usr/sbin, which is correct!  But our systemd units still have it in /usr/bin which means that it fails now.
> Samba fix startup

- utils/smartmontools/DETAILS
How is not having a sha256 sum even allowed?
> smartmontools: Adding a sha256sum.

- web/httpd/DETAILS
- web/httpd/PRE_BUILD
Note that with this release, httpd 2.2 is now at its end-of-life, so if
you haven't done so already, you should migrate to httpd 2.4.
> httpd: Version bump to 2.2.34.

- crypto/bitcoin/DETAILS
As it says on their github page:
> Preferably use the above download link, not the below links to
> download the source tarball, as the release tarballs are generated
> deterministically and GitHub's are not.
> Fixed the URL for bitcoin-core.

- graphics/ImageMagick/BUILD
- sql/virtuoso/DEPENDS
- sql/virtuoso/DETAILS
- sql/virtuoso/PRE_BUILD
/usr/lib/perl5/5.26.1/x86_64-linux-thread-multi/CORE/perl.h:738:13: fatal error: xlocale.h: No such file or directory
That means you went for the glibc-2.26 bump. This is the second module I ran into (well perl) that uses xlocale.h in past
versions of glibc. Well the glibc folks dropped that header and now you only have locale.h. Why, dunno but the short of it,
relin perl and you should be good to go.
Oh and I fiddled with a few other depends, best guess.
> virtuoso: bump to 7.2.4.2. If you say yes to perl and run into this;

- utils/microcode/DETAILS
Does anyone know where the "microcode_ctl" command comes from?
> Intel microcode: Updated to 20180108.

- net/whois/DETAILS
The previous version, 5.2.20, seems to have been completely bogus.
> whois: Version bump to 5.3.0.

- utils/cronie/systemd.d/cronie.service
Seems the latest release of cronie moves crond into /usr/sbin, which is
to be fair where it should have been all along anyway.
> cronie.service: Fixed systemd unit file.

- filesys/zfs-utils/DETAILS
- filesys/zfs/DETAILS
- kernel/spl/DETAILS
It compiles now with Linux kernel version 4.15.x.
> zfs: version bumped to 0.7.6

- audio/beep/patch.d/CVE-2018-0492.patch
- audio/beep/patch.d/catch-sig-term.patch
Here are a couple of patches from the guys at Debien:
1) catch-sig-term.patch: If someone bangs on ^C halfway through a beep, make the PC speaker shut up, and
2) CVS-2018-0492.patch: The beep command had a security problem!  Imagine that being how your system got rooted.  How embarrassing would that be?
> Beep patches

- editors/emacs/DEPENDS
- editors/emacs/DETAILS
Also added the new optional dependencies as outlined in the release notes.
> emacs: Version bumped to 26.1.

- python/python2-httplib2/DEPENDS
- python/python2-httplib2/DETAILS
Newer releases of httplib2 don't work with Python 2 any more.
(This also requires the next release of "Lunar", because it uses
the default Python2 build, instead of having its own BUILD.)
> python2-httplib2: New module

- libs/poppler/DEPENDS
- libs/poppler/DETAILS
openjpeg-2 and `%JPEG` have to be regular dependencies, otherwise the build breaks without them.
> poppler: Update to 0.68.0 & make openjpeg-2 and `%JPEG` regular deps

- filesys/fuse/DETAILS
fuse:Change download URL to https
And the releases is 3.2.6 now.
https://github.com/libfuse/libfuse/releases
> fuse:Change download URL to https

- compilers/mozjs/BUILD
- compilers/mozjs/CONFIGURE
- compilers/mozjs/DETAILS
- compilers/mozjs/PRE_BUILD
- devel/polkit/BUILD
- devel/polkit/patch.d/mozjs-60.patch
polkit needs a patch for compiling successfully against mozjs60.
this patch is already applied as PR in polkit's gitlab, see url bellow
https://gitlab.freedesktop.org/polkit/polkit/merge_requests/4
> mozjs version bump to mozjs60

- web/httpd/DETAILS
- web/httpd/systemd.d/httpd.service
You can either make the service type "simple" and start httpd
with the "-DFOREGROUND" flag, or call it "forking", and start
it without that flag.
You can't have it sort of half way.  That just results in an httpd
service that mysteriously times out because it isn't behaving the way
systemd expects it to behave..
> httpd: Fix the systemd service file.

- net/bind/DETAILS
We seriously need to set moonbase-other to be PR-only.  The number of
terrible, broken commits here lately is just unacceptable.
> bind: Fixing module name.

- graphics/freetype2/DETAILS
- graphics/freetype2/PRE_BUILD
The patches completely failed to apply, so I'm going to just to assume
that the problems that the patches sorted out were fixed within
freetype2 itself.
> freetype2: Version bumped to 2.10.0

- utils/chrono/DETAILS
Now process months and years. 
Also fixed a bug in the countdown parsing code.
Rewrote time string display function.
> chrono: version bumped to 0.2.27

- utils/chrono/DETAILS
-Now reset even when paused.
-Count seconds_total according to months of 28/29/30/31 days.
-Handle leap year
-Added tests for years and months parsing
> chrono: version bumped to 0.2.29

- x11-utils/pinentry/DEPENDS
pinentry has an optional_depends on gcr.
gcr requires gnupg.
gnupg requires pinentry.
pinentry -> gcr -> gnupg -> pinentry -> gcr -> etc
This PR adds a warning to the optional_depends, and defaults to choosing no.
> pinentry: added warning about circular dependency

- compilers/mozjs/DEPENDS
- compilers/mozjs/PRE_BUILD
Mozjs checks for rustc, and fails if it's not found. However, it does not use rustc at all. It defaults to using clang if it's installed, and falls back to gcc.
- PRE_BUILD has been modified with a sed line ( lifted from http://linuxfromscratch.org/blfs/view/systemd/general/js68.html ) that removes the rustc check.
- DEPENDS adds an optional_depends for llvm.
> Mozjs: Changes to dependencies

- utils/bashtop/DETAILS
bashtop: version bumped to 0.8.28.
> bashtop: version bumped to 0.8.28.

- utils/bashtop/DETAILS
bashtop: version bumped to 0.8.30.
>  bashtop: version bumped to 0.8.30.

- utils/bashtop/DETAILS
bashtop:version bumped to 0.9.6.
> bashtop:version bumped to 0.9.6.

- utils/bashtop/DETAILS
bashtop:version bumped to 0.9.9.
> bashtop:version bumped to 0.9.9.

- libs/intel-tbb/BUILD
Small change on the output dir which starts with "linux_intel*" on 64bit systems but is generated as "linux_ia32*" on 32bit systems.
> intel-tbb: fix broken install for 32bit systems

- devel/polkit/DEPENDS
- devel/polkit/DETAILS
Version bump to 117 - fixes GCC 10 compatibility, and updated to use newer mozjs.
> Polkit - version bump, mozjs, gcc 10

- compilers/mozjs78/BUILD
- compilers/mozjs78/CONFIGURE
- compilers/mozjs78/DEPENDS
- compilers/mozjs78/DETAILS
- compilers/mozjs78/PRE_BUILD
Gnome is already using mozjs 78 - gjs fails without it.
This is almost unchanged from the mozjs already found in the moonbase.
> mozjs78 - new version

- graphics/geeqie/BUILD
- graphics/geeqie/DEPENDS
- graphics/geeqie/DETAILS
- graphics/geeqie/PRE_BUILD
- Version bump to 1.6
- There's a problem with gpu acceleration (clutter-gtk -> libX11). It's a known issue, and will hopefully be patched soon.
See: https://github.com/BestImageViewer/geeqie/issues/829, which leads to
https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/125
> geeqie - version bump

- devel/gdb/DEPENDS
Gdb supports source highlighting of the debugged program throught source-highlight module.
This behavior can be controlled at runtime by set style sources ‘on|off’ in the gdb console or the .gdbinit file
> gdb: Add source-highlight as an optional dependency

- graphics/libopenraw/BUILD
- graphics/libopenraw/DEPENDS
- graphics/libopenraw/DETAILS
- graphics/libopenraw/PRE_BUILD
tweaks to the recent 0.3.0 update
- BUILD: the sedit breaks the build if it's used (error: 'JPEG' has not been declared), and has been removed.
- DEPENDS: moved gdk-pixbuf to optional_depends, and added rustc option.
- DETAILS: I'm still using the .xz instead of the .bz2. Let's save upstream a 100K of bandwidth.
- PRE_BUILD: fixes an error with the openraw-gnome pkgconfig file. This has been merged upstream.
> libopenraw - 0.3.0 updates

- graphics/GraphicsMagick/DEPENDS
- added some optional_depends available in the configuration
- specifically removed ufraw in favour of libopenraw (openraw is better as a backend processor, and ufraw hasn't been updated in 5 years).
> GraphicsMagick - update DEPENDS

- graphics/GraphicsMagick/DEPENDS
- graphics/GraphicsMagick/DETAILS
- version bump to 1.3.36
- removed some un-necessary depends (bzip and xz are already installed by default)
> Graphics magick

- graphics/geeqie/BUILD
- graphics/geeqie/DEPENDS
- graphics/geeqie/patch.d/f34ea0700048c27319a2256408171adda32a7580.patch
The 1.6 update had a known bug where gpu acceleration (using clutter) was causing segfaults. This PR includes a patch that fixes the problem, and restores clutter as a DEPENDS option.
> geeqie - patch to fix clutter render

- doc-tools/docutils/POST_INSTALL
libdrm's configuration fails without this link from rst2man.py to rst2man with this message:  
```
[...]
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/lib/qt5/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/opt/share/pkgconfig'
Run-time dependency cairo found: YES 1.16.0
Program rst2man found: NO
meson.build:264:0: ERROR: Program 'rst2man' not found
A full log can be found at /usr/src/libdrm-2.4.104/build/meson-logs/meson-log.txt
Creating /var/log/lunar/compile/libdrm-2.4.104.xz 
! Problem detected during BUILD
```
> docutils: add link for libdrm

- audio/speech-dispatcher/PRE_BUILD
I had this error on my laptop and server:  
```
[...]
make[5]: Leaving directory '/usr/src/speech-dispatcher-0.10.2/src/api/python/speechd'
Making all in speechd_config
make[5]: Entering directory '/usr/src/speech-dispatcher-0.10.2/src/api/python/speechd_config'
rm -f config.py
rm -f paths.py
srcdir=; \
test -f ./config.py.in || srcdir=./; \
sed -e "s:[@]GETTEXT_PACKAGE[@]:speech-dispatcher:" -e "s:[@]VERSION[@]:0.10.2:" -e "s:[@]localedir[@]:/usr/share/locale:" ${srcdir}config.py.in > config.py
srcdir=; \
test -f ./paths.py.in || srcdir=./; \
sed -e "s:[@]spdconforigdir[@]:/usr/share/speech-dispatcher/conf:" -e "s:[@]spdconfdir[@]:/etc/speech-dispatcher:" -e "s:[@]snddatadir[@]:/usr/share/sounds/speech-dispatcher:" -e "s:[@]spddesktopconforigdir[@]:/usr/share/speech-dispatcher/conf/deskto …
```
> speech-dispatcher: fix build error

- doc-tools/atril/BUILD
- doc-tools/atril/DEPENDS
- doc-tools/atril/DETAILS
Part of the MATE desktop, Atril is functionally identical to Evince, but without the GNOME dependencies.
_Note:_ Version 1.25 is a testing version (but very stable, incremental changes from 1.24). It includes the option to disable synctex, which we don't have in the Moonbase.
> Atril - document viewer

- web/node/DEPENDS
- Node uses Python v3 by default, updated DEPENDS.
- Also removed unused dependency on 'v8'
> node - use Python3

- libs/nspr/BUILD
Fix the condition where on 32 bit the whole process chain fails because the arch program doesn't return "x86_64". In this case simply removing the chaining && at the end of the line fixes this bug.
Here's the output without the fix:  
```
root@PC04 ~ # time lin nspr
+ Editing "/etc/lunar/local/depends/nspr"
+ Spawning download manager
+ download queue:  nspr
+ starting lin "nspr"
+ downloading module "nspr"
+ Skipping download of "nspr-4.29.tar.gz" (in cache)
Building nspr version 4.29
+ running "default_pre_build"
+ validating "/usr/src/nspr-4.29"
+ creating building dir "/usr/src/nspr-4.29"
+ Removing old source directory first!
+ destroying building dir "/usr/src/nspr-4.29"
+ Unpacking "/var/spool/lunar/nspr-4.29.tar.gz" in "/usr/src"
+ building "nspr" version "4.29" in …
```
> nspr: fix build error on 32bit machines

- libs/apr-util/BUILD
Got this output:
```
[...]
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking for working mkdir -p... yes
APR-util Version: 1.6.1
checking for chosen layout... apr-util
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
Applying apr-util hints file rules for x86_64-pc-linux-gnu
checking for APR... no
configure: error: APR …
```
> apr-util: fix configure error

- games/openttd/BUILD
- games/openttd/DEPENDS
- games/openttd/DETAILS
- games/openttd/INSTALL
Lots of fixes into this :)
The build system is now cmake
https://github.com/OpenTTD/OpenTTD/releases
> openttd: version bumped to 1.11.0

- libs/libpsl/BUILD
- libs/libpsl/DEPENDS
- libs/libpsl/POST_INSTALL
- libs/libpsl/PRE_BUILD
- net/publicsuffix-list/DETAILS
libpsl:
DEPENDS - fixed an error in the gtk-doc optional_depends that causes a configure failure if you chose to _not_ install (libpsl defaults to enabling docs).
PRE_BUILD - autoreconf doesn't read the OPTS in the DEPENDS file (because PRE_BUILD is finished before DEPENDS is read), which meant the gtk-doc failure still happened. It's not necessary to the build anyway.
BUILD - using default_build works properly, even with the exported LC_CTYPE (why aren't we using the system default?). This makes the autoreconf in PRE_BUILD unnecessary.
POST_INSTALL - since we're deleting the suffix list in PRE_BUILD, I added in this implicit install of _publicsuffix-list,_ which is the whole point to libpsl.
publicsuffix-list:
DETAILS: updated to the most recent commit.
> libpsl + publicsuffix-list fixes

- graphics/darktable/BUILD
- graphics/darktable/DEPENDS
- graphics/darktable/DETAILS
- graphics/darktable/PRE_BUILD
Whole bunch of changes - the darktable module hasn't been updated in over a year.
BUILD - darktable either requires gcc to be compiled with isl support, or clang to be used as a compiler instead. Since clang will already be installed as part of the dependency chain (gtk+-3 > mesa-lib > llvm), it's easier & safer to use clang.
DEPENDS - this has been almost entirely rewritten because of changes between v2.6 and v3.4
DETAILS - Normal version bump changes.
PRE_BUILD - darktable only checks up to v11.0 of llvm, I've added a sed line to include v11.1.
> darktable update

- audio/deadbeef/BUILD
- audio/deadbeef/DEPENDS
- audio/deadbeef/DETAILS
- audio/deadbeef/PRE_BUILD
BUILD:
- gtk2 is now legacy code, and upstream will stop supporting it soon.
- last.fm and notification support require swift/libdispatch, which we don't have on Lunar.
DEPENDS:
- made gtk3 the default
- fixed an error in the faad2 optional_depends
DETAILS:
normal version bump updates
PRE_BUILD:
there's a string replacement that doesn't seem to be necessary anymore (compiled and works fine without it), but I've commented it out and left it here in case I'm wrong and it is needed.
> deadbeef - version bump

- libs/qrencode/DEPENDS
_qrencode_ installs using SDL2 without problems. I think we should use the newer library when possible.
> qrencode - update DEPENDS

- graphics/graphite/DEPENDS
Graphite no longer needs python2, and probably has not for a while. This was probably an old DEPENDS that was never updated because it never actually failed to build.
> graphite - update DEPENDS

- python/python-appdirs/DEPENDS
- python/python-appdirs/DETAILS
A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir"
This module is for multi-platform apps to figure out the correct directory structure to use when storing user data.
From the homepage:
> What directory should your app use for storing user data? If running on Mac OS X, you should use:
> 
> ~/Library/Application Support/<AppName>
> 
> If on Windows (at least English Win XP) that should be:
> 
> C:\Documents and Settings\<User>\Application Data\Local Settings\<AppAuthor>\<AppName>
> 
> or possibly:
> 
> C:\Documents and Settings\<User>\Application Data\<AppAuthor>\<AppName>
> 
> for roaming profiles but that is another story.
> 
> On Linux (and other Unices) the dir, according to the XDG spec, is:
> 
> ~/.local/share/<AppName>
This module is …
> new module - python-appdirs

- x11-utils/engrampa/BUILD
- x11-utils/engrampa/DEPENDS
- x11-utils/engrampa/DETAILS
Part of the Mate Desktop, _engrampa_ is a fork of GNOME 3's _file roller,_ but without the extra GNOME dependencies.
> engrampa - archive manager

- x11-apps/mate-calc/DEPENDS
- x11-apps/mate-calc/DETAILS
Part of the Mate Desktop, _mate-calc_ is a fork of _gnome calculator, _ but without the GNOME dependencies.
> mate-calc - desktop calculator

- utils/syslog-ng/BUILD
- utils/syslog-ng/DETAILS
Currently running syslog-ng gives those messages:
> [2021-08-04T12:28:26.094620] Error resolving group; group='log'
syslog-ng: Error changing to directory=/run--enable-systemd, errcode=2
[2021-08-04T12:28:26.805680] Error opening control socket, bind() failed; socket='/run--enable-systemd/syslog-ng.ctl', error='No such file or directory (2)'
syslog-ng: Error creating pid file; file='/run--enable-systemd/syslog-ng.pid', error='No 
such file or directory'
> syslog-ng: version bump and fix typo in BUILD

- kernel/lttng-modules/BUILD
- kernel/lttng-modules/DEPENDS
- kernel/lttng-modules/DETAILS
This is PR 1/3.  Please merge this first before testing the next.
> lttng-modules: New module, the kernel modules for the LTTng system tracer.

- devel/lttng-ust/BUILD
- devel/lttng-ust/DEPENDS
- devel/lttng-ust/DETAILS
This is PR 2/3.  Please merge this before merging lttng-tools.
> lttng-ust: New module, libraries used by the LTTng tracer.

- graphics/GraphicsMagick/BUILD
- graphics/GraphicsMagick/DEPENDS
- graphics/GraphicsMagick/DETAILS
BUILD: _--enable-symbol-prefix_ causes several of the programs to fail if ImageMagick is also installed. Static files were disabled, and X support is implicitly included.
DEPENDS: added some missing deps, and GM requires ghostscript now.
> updated depends & build

- graphics/darktable/BUILD
- graphics/darktable/DEPENDS
- graphics/darktable/DETAILS
BUILD: removed a couple of redundant OPTS (both are ON by default)
DEPENDS: moved _openexr_ from a hard dependency to an _optional,_ added _isl_ as a hard dep, and g'mic as an optional
DETAILS: normal version bump changes
> darktable version bump

- virtual/conmon/DEPENDS
- virtual/conmon/PRE_BUILD
The error message I had was:
`meson.build:37:0: ERROR: Unknown variable "cc".`
> conmon: add missing meson code

- devel/polkit/DETAILS
- devel/polkit/patch.d/polkit-0.120-pkexec.patch
Local users can become root without much difficulty (but this patch
fixes that).
> policykit: Add patch to close CVE-2021-4034 security hole

- graphics/gphoto2/DEPENDS
libexif is no longer optional in gphoto2
> gphoto2: fix depends

- graphics/librsvg/CONFIGURE
- graphics/librsvg/DEPENDS
CONFIGURE: the _miscellaneous tools_ option doesn't exist anymore
DEPENDS:
- pango requires cairo on Lunar by default
- gtk-doc is optional
- gobject-introspection had a typo (both _yes_ and _no_ were set to _enable_)
- made the disable options for both _vala_ and _introspection_ match what's in the ./configure file.
> librsvg: fix depends

- web/firefox-bin/BUILD
- web/firefox-bin/DETAILS
- web/firefox-bin/DETAILS.x86_64
BUILD:
- the _/usr/lib/firefox/browser/icons/_ folder no longer exists, and neither does the _mozicon128.png_ file. I changed this to something that actually works.
DETAILS:
- normal version bump changes
> firefox-bin: version bump

- virtual/containerd/BUILD
The containerd binary was being installed in /usr/usr/local/bin/containerd
> containerd: fix wrong installation path

- science/qhull/BUILD
- science/qhull/DETAILS
WARNING: Qhull library not found.  This will result in loss of functionality for some geometry functions
> qhull: Adjusting BUILD to silence this warning during an octave compile;

- audio/gst-libav/DEPENDS
gst-libav:depends elfutils to fix https://github.com/lunar-linux/moonbase-other/issues/1861
> gst-libav:depends elfutils

- web/httpd/DETAILS
This release fixes 8 CVEs  
https://downloads.apache.org/httpd/CHANGES_2.4
> httpd: version bumped to 2.4.54

- libs/apr/DETAILS
The main site says:
`Do not download from www.apache.org. Please use a mirror site to help us save apache.org bandwidth.`
So the CDN link should be used here too.
> apr: use CDN link instead

- libs/apr-util/DETAILS
The main site says:
`Do not download from www.apache.org. Please use a mirror site to help us save apache.org bandwidth.`
So use the CDN link instead.
> apr-util: use CDN link instead

- web/httpd/DETAILS
The main site mentions:  
`Do not download from www.apache.org. Please use a mirror site to help us save apache.org bandwidth.`
So the CDN (Content Delivery Network)  link should be used instead.
> httpd: opt for the CDN instead

- doc-tools/docbook-utils/DETAILS
The URL from RedHat was broken, so use the URL that BLFS uses.
> docbook-utils: fix broken URL

- filesys/mtools/DETAILS
This was causing mtools to always be candidate in the update list when running `lunar update`
> mtools: fix typo in UPDATED

- x11-wm/fluxbox/PRE_BUILD
The build was giving:
`util/fluxbox-remote.cc:76:32: error: ordered comparison of pointer with integer zero ('unsigned char*' and 'int')
76 |             && text_prop.value > 0`
so introduce a fix for comparison with NULL instead.
> fluxbox: fix pointer comparison to zero error

- python/python-asn1crypto/DEPENDS
- python/python-asn1crypto/DETAILS
- python/python-cffi/DEPENDS
- python/python-cffi/DETAILS
- python/python-idna/DEPENDS
- python/python-idna/DETAILS
- python/python-ply/DEPENDS
- python/python-ply/DETAILS
- python/python-pyasn1/DEPENDS
- python/python-pyasn1/DETAILS
- python/python-pycparser/DEPENDS
- python/python-pycparser/DETAILS
It's only "needed" for one function used in one module in core (ca-certificates) and that module doesn't even do anything with what it uses python-cryptography for, so to make life simpler, I just removed the requirement for python-cryptography to be in core.
This is python-cryptography from core, and all of its dependencies.
> Python-cryptography: moving it to moonbase-other

- compilers/php/DEPENDS
- compilers/php/DETAILS
Fixes CVE-2022-31630 and CVE-2022-37454
https://www.php.net/ChangeLog-8.php#8.1.12
> php: version bumped to 8.1.12

- utils/gpm/profile.d/gpm.rc
When login in a tty the message "pidof: invalid session id: gpm" appears.
So redirect stderr to /dev/null.
> gpm: remove annoying error message after login

- filesys/zfs-utils/DETAILS
- filesys/zfs/DETAILS
Includes support for Linux 6.1, grep 3.8
> zfs, zfs-utils: Bump to 2.1.9

- mail/postfix/DETAILS
Note that postfix-3.7.2 seems to have been deleted from postfix.org. I wonder what was wrong with it.
> postfix: Bump to 3.7.4

- mail/mutt/DEPENDS
I wonder if we can do some sort of automated monitoring for modules that depend on stuff that's been cratered
> mutt: change mime-types dependency to media-types

- compilers/mozjs91/BUILD
- compilers/mozjs91/CONFIGURE
- compilers/mozjs91/DEPENDS
- compilers/mozjs91/DETAILS
New version of mozjs that uses the latest Firefox ESR.
Note: PRE_BUILD was integrated into BUILD, and there's no longer an option to remove the js-shell, so the CONFIGURE option and it's if statement in BUILD were removed.
> mozjs version 91

- web/httpd/BUILD
- web/httpd/DETAILS
Fixes CVE-2023-27522 and CVE-2023-25690 amongst other fixes.
https://dlcdn.apache.org/httpd/CHANGES_2.4.56
> httpd: version bumped to 2.4.56

- compilers/rustc/BUILD
Default to 1 build at a time if MAKES isn't set to some other value, just like how the rest of the system works.
> rustc: Fix broken build when MAKES isn't set

- compilers/camlp4/BUILD
- compilers/camlp4/DEPENDS
- compilers/camlp4/DETAILS
> camlp4: Bump to 5.0.0+1. Yes its still in 4.x but adjusted to compile

- perl/Locale-gettext/DETAILS
Actually the original site fixed the download URL.
> Local-gettext: Fixed download URL

- python/python-attrs/BUILD
- python/python-attrs/DEPENDS
- python/python-attrs/DETAILS
- python/python-attrs/POST_INSTALL
installing, and a POST_INSTALL cause of byte compiling.
> python-attrs: Bump to 23.1.0. Requires a BUILD for their new way of

- compilers/go-bootstrap2/BUILD
- compilers/go-bootstrap2/CONFIGURE
- compilers/go-bootstrap2/DEPENDS
- compilers/go-bootstrap2/DETAILS
- compilers/go-bootstrap2/POST_INSTALL
- compilers/go-bootstrap2/PRE_BUILD
- compilers/go/BUILD
- compilers/go/DEPENDS
- compilers/go/DETAILS
- compilers/go/POST_INSTALL
- compilers/go/PRE_BUILD
This expands _greatly_ on #2346--going from nothing to go 1.20.5 requires a boot strap from C to Go 1.4, and then yet another bootstrap from Go 1.4 to Go 1.19. So this PR adds that second bootstrap.
> Go - bump to 1.20.5 (and add second bootstrap)

- games/openttd/BUILD
- games/openttd/DEPENDS
- games/openttd/INSTALL
Strangely the unpacking of the game files seem to be ignored if put in INSTALL, so move everything in BUILD.
Note that an attempt was made to put the unpack calls in POST_INSTALL, and it works, but installwatch doesn't track those at this point and it was breaking resurrection of the module. Now it works :)
> openttd: move unpack ops into BUILD

- utils/chrono/DETAILS
- Fixes build error on systems where ncurses.h is not in /usr/include/ncursesw/.
> chrono: version bumped to 0.2.44

- chat/weechat/BUILD
- chat/weechat/DEPENDS
- chat/weechat/DETAILS
Now there's this message showing up when configuring:
[...]
CMake Error at CMakeLists.txt:154 (message):
All plugins are required to build documentation.
If you really want to build incomplete docs, enable this option:
-DENABLE_DOC_INCOMPLETE=ON
> weechat: version 4.0.4 + allow incomplete docs

- virtual/qemu/BUILD
By default qemu configures with the system fdt, so use the internal one instead.
I was getting:
[...]
RDMA support                                 : NO
PVRDMA support                               : NO
fdt support                                  : system
libcap-ng support                            : YES
bpf support                                  : NO
[...]
\+ saving library "/usr/lib/qemu/ui-opengl.so"
\+ saving library "/usr/lib/qemu/ui-sdl.so"
\+ calling "lrm --upgrade qemu"
\+ updating lunar state files after module removal
Removed module: qemu
changing dir to build for /usr/bin/make "install"...
make[1]: Entering directory '/usr/src/qemu-8.1.0/build'
ninja: error: '/usr/lib/libfdt.a', needed by 'qemu-system-aarch64', missing and no known rule to make it
make[1]: *** [Makefile:162: …
> qemu: fix build error with missing libfdt.a

- graphics/libwebp/DETAILS
Caught in my emails, from a Slackware security release:
"Security fix for lossless decoder (chromium: #1479274, CVE-2023-4863)"
> libwebp: version bumped to 1.3.2

- science/OpenBLAS/DEPENDS
- science/OpenBLAS/DETAILS
Armadilo looks for atlas and/or OpenBLAS. In its compile log it is clear atlas will be depreciated and if both is present will ignore atlas in favor of OpenBLAS. No switches are needed.
> OpenBLAS: Adding. Will be a depends for armadilo bump.

- web/nghttp2/DETAILS
Fixes [CVE-2023-44487](https://github.com/nghttp2/nghttp2/security/advisories/GHSA-vx74-f528-fxqg)
> nghttp2: version bumped to 1.57.0

- video/libvpx/DETAILS
Fixes CVE-2023-5217 (heap buffer overflow)
> libvpx: version bumped to 1.13.1, security fix

- x11-utils/libxkbcommon/DETAILS
Reverts lunar-linux/moonbase-other#3112 which breaks qt5.
> Revert "libxkbcommon: version bumped to 1.6.0"

- video/libprojectM/DEPENDS
- video/libprojectM/DETAILS
- video/libprojectM/PRE_BUILD
Adjusted PRE_BUILD to see if it really uses/needs qt5. Greping the compile for qt revealed no results. We shall see.
> libprojectM: Bump to 4.0.0. Now uses cmake.

- graphics/ocaml-cairo/DETAILS
Locally, this fails with;
/usr/include/cairo/cairo-ft.h:46:10: fatal error: ft2build.h: No such file or directory
Of course the file exists and ft2build.h is in the header.
> ocaml-cairo: This is a test between ocaml-cairo and cairo on CI.

- science/sphinx/sphinxtrain/DEPENDS
- science/sphinx/sphinxtrain/DETAILS
Depends sphinxbase is depreciated and will be moved to crater. This module now depends on pocketsphinx.
> sphinxtrain: Bump to 5.0.0. Converted to cmake.

- net/bind-utils/BUILD
The utilities fail to execute because of missing shared libraries. Taken from the LinuxFromScratch book (BLFS-dev).
> bind-utils: install missing libs

- printer/pspdfutils/BUILD
- printer/pspdfutils/DEPENDS
- printer/pspdfutils/DETAILS
installation section mention is made of using pypi.org as the source url. Note the naming; pspdfutils.
The three modules dependent on psutils, groff, a2ps and texlive, compile fine with this version.
> pspdfutils: Adding. This will replace psutils. Here in the

- printer/foomatic-db-engine/DETAILS
"current" foomatics because they change often. This would cause un-needed effort maintaining them, unless you disable sha256, which we prefer *not* to do.
If you want them bumped, a copy needs to be uploaded to mirrors on robusta. For those without acces, I'm generally around so message if in need when you decide to bump any of the foomatic stuff.
> foomatic-db-engine: Bump to 4.0-20231024. We don't use any of the

- graphics/darktable/DEPENDS
- graphics/darktable/DETAILS
- graphics/darktable/PRE_BUILD
- graphics/darktable/patch.d/darktable-3.4.0_jsonschema-automagic.patch
- graphics/darktable/patch.d/libavif-1.patch
gentoo folks dealing with json stuff and one from arch folks dealing with with libavif.
> darktable: Bump to 4.4.2. Adding two patches, notable one from the

- libs/fftw/BUILD
get created during the build, thus not installed. This file is needed by krita during its cmake configuration stage.
> fftw: Adjusting BUILD. As is, FFTW3LibraryDepends.cmake does not

- devel/git/DEPENDS
Since the `depends.cache` file uses colons as field separators, colons in the optional_depends explanations confuses anything trying to parse it.
> git: semi-cosmetic fix to DEPENDS file

- compilers/tcc/DETAILS
This module was failing with:
[...]
ar rcs libtcc.a libtcc.o tccpp.o tccgen.o tccelf.o tccasm.o tccrun.o x86_64-gen.o x86_64-link.o i386-asm.o
gcc -o tcc tcc.o libtcc.a -lm -ldl -s -Wl,-z,relro,-z,now,--sort-common 
make[1]: Entering directory '/usr/src/tcc-0.9.27/lib'
../tcc -c libtcc1.c -o libtcc1.o -B..
../tcc -c alloca86_64.S -o alloca86_64.o -B..
../tcc -c alloca86_64-bt.S -o alloca86_64-bt.o -B..
../tcc -c va_list.c -o va_list.o -B..
../tcc -c bcheck.c -o bcheck.o -B..
bcheck.c:738: error: '__malloc_hook' undeclared
make[1]: *** [Makefile:64: bcheck.o] Error 1
make[1]: Leaving directory '/usr/src/tcc-0.9.27/lib'
make: *** [Makefile:230: libtcc1.a] Error 2
According to the home page the project is unmaintained but there's a github repo that seems active and which have fixed this …
> tcc: use clone, now working with the newer glibc

- devel/git/DETAILS
Weirdly the build process fails if passing --with-libpcre2 instead of --with-libpcre
> git: version bumped to 2.43.0

- utils/jq/BUILD
- utils/jq/DETAILS
Fixes 2 CVEs:
CVE-2023-50246: Fix heap buffer overflow in jvp_literal_number_literal
CVE-2023-50268: fix stack-buffer-overflow if comparing nan with payload
> jq: version bumped to 1.7.1 (security fix)

- mail/postfix/DETAILS
This includes a fix for https://www.postfix.org/smtp-smuggling.html wherein an attacker can fool your mail server into delivering emails to where it's not supposed to, via the magic of poorly-formed line endings.
> postfix: Version bumped to 3.8.4

- wayland/xwayland/DETAILS
Fixes 6 CVEs:
1) CVE-2023-6816 can be triggered by passing an invalid array index to DeviceFocusEvent or ProcXIQueryPointer.
2) CVE-2024-0229 can be triggered if a device has both a button and a key class and zero buttons.
3) CVE-2024-21885 can be triggered if a device with a given ID was removed and a new device with the same ID added both in the same operation.
4) CVE-2024-21886 can be triggered by disabling a master device with disabled slave devices.
5) CVE-2024-0409 can be triggered by enabling SELinux xserver_object_manager and running a client.
6) CVE-2024-0408 can be triggered by enabling SELinux xserver_object_manager and creating a GLX PBuffer.
> xwayland: version bumped to 23.2.4

- x11-apps/xsel/DETAILS
- x11-apps/xsel/PRE_BUILD
The configure script was running twice, so fix that with autoreconf.
> xsel: fix hash and prevent double configure

- video/MPlayer/BUILD
- video/MPlayer/DEPENDS
- video/MPlayer/DETAILS
- video/MPlayer/MPlayer-1.5-upstream_ffmpg6_fixes-1.patch
- video/MPlayer/PRE_BUILD
- video/MPlayer/ffmpeg-6.0-binutils_2.41-1.patch
the changelog live555 is disabled by default and scheduled to be removed. Also in the BUILD, mplayer has always been a bit touchy about compile options and unsetting compiler wasn't enough, just remove $OPTS.
Added a couple of patches from the LFS folks. Thank you guys.
This will no doubt fail on CI.
> MPlayer: Bump to 1.5. Removed MPlayer-all and MPlayer-essentials. Per

- devel/strace/BUILD
- devel/strace/DETAILS
The libunwind headers live in /usr/include
> strace: version bumped to 6.7

- archive/pigz/BUILD
- archive/pigz/DETAILS
pushd and popd add unnecessary output, so reduce noise with a simple ln command.
> pigz: version bumped to 2.8

- filesys/glusterfs/DEPENDS
- filesys/glusterfs/DETAILS
- filesys/glusterfs/tmpfiles.d/glusterfs.conf
Systemd was giving this message:
Line references path below legacy directory /var/run/, updating /var/run/glusterfs → /run/glusterfs; please update the tmpfiles.d/ drop-in file accordingly.
> glusterfs: version bumped to 11.1

- libs/poppler/BUILD
- libs/poppler/DEPENDS
- libs/poppler/DETAILS
poppler missing lcms2. Making lcms2 a depends.
> poppler: Bump to 24.02.0. Per PR3483, pypoppler failed on

- net/keepalived/DETAILS
This can come in quite handy for high-availability-type situations.
> keepalived: New module

- video/freshplayerplugin/BUILD
- video/freshplayerplugin/DEPENDS
- video/freshplayerplugin/DETAILS
Per; https://github.com/i-rinat/freshplayerplugin/issues/389, disabling hardware decoding.
If and when this module breaks again I highly recommend it be sent off to /dev/null, it doesn't deserve crater.
> freshplayer: Bump to 0.3.11. Reworked DEPENDS and adjusted BUILD.

- archive/zziplib/BUILD
The .pc files seem to be incorrectly generated. The installed libs end in -0.so so add a temporary fix until this situation is resolved upstream.
> zziplib: fix wrong libs in pkgconfig file

- web/httpd/DETAILS
Fixes 3 CVEs: [CVE-2023-38709](https://www.cve.org/CVERecord?id=CVE-2023-38709) [CVE-2024-24795](https://www.cve.org/CVERecord?id=CVE-2024-24795) and [CVE-2024-27316](https://www.cve.org/CVERecord?id=CVE-2024-27316)
> httpd: version bumped to 2.4.59

- utils/kexec-tools/DETAILS
- utils/kexec-tools/patch.d/kexec-tools-binutils_2.42_fix.patch
The build was failing with:
purgatory/arch/i386/entry32-16.S:23: Error: 64bit mode not supported on `i386'.
> kexec-tools: version bumped to 2.0.28 + new patch

- filesys/zfs-utils/DETAILS
- filesys/zfs/DETAILS
This includes support for Linux 6.8 kernels, so it'll be nice for it to work with a recent daily ISO
> zfs: Version bumped to 2.2.4

- web/httpd/DETAILS
Fixes [CVE-2024-36387](https://www.cve.org/CVERecord?id=CVE-2024-36387), [CVE-2024-38472](https://www.cve.org/CVERecord?id=CVE-2024-38472), [CVE-2024-38473](https://www.cve.org/CVERecord?id=CVE-2024-38473), [CVE-2024-38474](https://www.cve.org/CVERecord?id=CVE-2024-38474), [CVE-2024-38475](https://www.cve.org/CVERecord?id=CVE-2024-38475), [CVE-2024-38477](https://www.cve.org/CVERecord?id=CVE-2024-38477) and [CVE-2024-39573](https://www.cve.org/CVERecord?id=CVE-2024-39573)
> httpd: version bumped to 2.4.60

- web/httpd/DETAILS
Fixes [CVE-2024-39884](https://www.cve.org/CVERecord?id=CVE-2024-39884)
> httpd: version bumped to 2.4.61

- audio/alsa-utils/BUILD
- audio/alsa-utils/DEPENDS
- audio/alsa-utils/DETAILS
--disable-xmlto to BUILD and removing xmlto optional_depends.
> alsa-utils: Bump to 1.2.12. Add switches --disable-rst2man and

- compilers/rustc/BUILD
- compilers/rustc/DETAILS
- compilers/rustc/config.toml
error[E0635]: unknown feature `stdsimd`
The sedit that was in BUILD about download-ci-llvm is now in config.toml. Additionally seems we were not actually using stable. The locked-deps and vendor entries puts us on stable.
Anyway, fixes libopenraw.
> rustc: Adding a config.toml. Started with libopenraw failing on;

- x11-wm/fluxbox/BUILD
- x11-wm/fluxbox/CONFIGURE
I was getting this error:
\+ running "default_make"
./src/defaults_tmp.cc ./src/defaults.cc differ: byte 224, line 9
make  all-recursive
make[1]: Entering directory '/usr/src/fluxbox-1.3.7'
Making all in nls/C
make[2]: Entering directory '/usr/src/fluxbox-1.3.7/nls/C'
conversion modules not available
make[2]: *** [Makefile:465: fluxbox.cat] Error 1
make[2]: Leaving directory '/usr/src/fluxbox-1.3.7/nls/C'
make[1]: *** [Makefile:4701: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/fluxbox-1.3.7'
make: *** [Makefile:1599: all] Error 2
Creating /var/log/lunar/compile/fluxbox-1.3.7.xz 
! Problem detected during BUILD
Disabling NLS support fixed it.
> fluxbox: make NLS support optional

- x11-utils/xinput_calibrator/BUILD
- x11-utils/xinput_calibrator/DETAILS
This is from the email I got:
```
This is the first release of xinput_calibrator after the move from
https://github.com/tias/xinput_calibrator to our gitlab instance. The
aim of this move is so this little tool, still in use here and there,
can see some of the benefits of group maintainership and doesn't go
completely stale. Don't expect active maintainership or new features
being added, we're just trying to keep this on life support.
The git shortlog below is for the ~14 years of patches since the 0.7.5
release, the last 10 of which the project was sitting idle.
```
Also the new URL is taken from this email.
> xinput_calibrator: version bumped to 0.8.0

- python/python-faust-cchardet/BUILD
- python/python-faust-cchardet/DEPENDS
- python/python-faust-cchardet/DETAILS
According to https://pypi.org/project/faust-cchardet/ python-cchardet it is no longer maintained. So this module will repace it. Before python-cchardet is removed, will have to wait unti CI updates itself with new modules.
> python-faust-cchardet: Adding. Will a depends for upcoming calibre bump.

- web/gumbo-parser/DETAILS
on the the information of the README from the origianl site; https://github.com/google/gumbo-parser/commit/a0f9059087c690e700cf42df4cfa58a63c1dae95
> gumbo-parser: Bump to 0.12.1. Changed SOURCE_URL and WEB_SITE based 

- libs/boost/DETAILS
- libs/boost/patch.d/003-boost-1.85.0-python-numpy-2.patch
dealing with numpy2. Which was the failure with PR#4094 (inkscape).
> boost: Adding a patch (thanks gentoo folks) fixing a compile issue

- utils/CPU-X/DETAILS
The new URL is a Github redirect from the old one. The new website URL is taken from the new Github profile description.
> CPU-X: version bumped to 5.0.4

- utils/powertop/DETAILS
- utils/powertop/PRE_BUILD
The old website URL redirects to intel.com, weird.
> powertop: version bumped to 2.15

- wifi/wireless-regdb/BUILD
- wifi/wireless-regdb/DETAILS
This module was installing in /usr/usr/lib/firmware :P
> wireless-regdb: version bumped to 2024.07.04 + fix wrong path

- utils/fwupd/DETAILS
The new URL is taken from a redirect from the original one.
> fwupd: version bumped to 1.9.23

- devel/gh/DETAILS
- devel/gh/PRE_BUILD
With the previous PRE_BUILD setup there was a leftover directory in /usr/src once lin is finished (cli-2.55.0).
> gh: version bumped to 2.55.0

- perl/Class-Autouse/patch.d/Class-Autouse-2.01-no-dot-inc.patch
I was getting this:
Can't locate inc/Module/Install/DSL.pm in @INC (you may need to install the  inc::Module::Install::DSL module) (@INC entries checked: /usr/lib/perl5/site_perl/5.40.0/  x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.40.0 /usr/lib/perl5/5.40.0/x86_64-linux-thread-multi /usr/lib/perl5/5.40.0) at Makefile.PL line 1.
> Class-Autouse: add Gentoo patch to fix build

- system/efitools/patch.d/efitools-1.9.2-gcc_14_extra_strictness.patch
gcc 14 is a lot stricter than gcc 13, so we have to deal with it until upstream gets around to it.
(Surely there's a better way to deal with the strptime issue than what I did though...)
> efitools: Add another patch file to deal with gcc 14

- utils/ripgrep/BUILD
- utils/ripgrep/DETAILS
Weird thing is 'rg --generate=...' shell completion generation doesn't seem to work in BUILD but does on the CLI.
> ripgrep: version bumped to 14.1.1

- net/wireguard-tools/BUILD
- net/wireguard-tools/DETAILS
It's worth noting that wireguard itself is now a standard part of the kernel, so there's no need for a separate module for that.
> wireguard-tools: Extra tools to manage WireGuard VPNs

- net/nftables/DETAILS
Note that this release of nftables requires the very latest libnftnl (1.2.8) over in core which currently has a PR waiting for verification, so this should probably not be merged until that one is ready.
> nftables: New module, provides the "nft" utility

- wayland/xwayland/DETAILS
Fixes CVE-2024-9632: Heap-based buffer overflow privilege escalation in _XkbSetCompatMap
> xwayland: version bumped to 24.1.4

- wifi/iwd/BUILD
- wifi/iwd/DETAILS
The readline pkgconfig file now resides in /usr/lib/pkgconfig and is found automatically. The systemd check is also removed since the other init systems have been taken out.
> iwd: version bumped to 3.1

- compilers/php/CONFIGURE
- compilers/php/DEPENDS
- compilers/php/DETAILS
Removed deprecated configure options. Fixes CVE-2024-8929, CVE-2024-8932, CVE-2024-11233, CVE-2024-11234, and CVE-2024-11236
> php: version bumped to 8.4.1

- archive/zlib-ng/BUILD
- archive/zlib-ng/DEPENDS
- archive/zlib-ng/DETAILS
over write a couple of headers and zlib.pc from core. This way no zlib files are trampled.
> zlib-ng: Adding. Compatibility mode left disabled since it would

- archive/minizip-ng/BUILD
- archive/minizip-ng/DEPENDS
- archive/minizip-ng/DETAILS
over write a pc file from minizip.
> minizip-ng: Adding. Comaptibility is left disabled so it does not

- libs/libfido2/DEPENDS
- libs/libfido2/DETAILS
depreciated and not maintained. libfido2 is recommended.
> libfido2: Adding. Per; https://github.com/Yubico/libu2f-host is

- graphics/FreeImage/BUILD
The error I was getting was:
```
Source/ZLib/gzlib.c: In function 'gz_open':
Source/ZLib/gzlib.c:14:17: error: implicit declaration of function 'lseek'; did you mean 'fseek'? [-Wimplicit-function-declaration]
14 | #  define LSEEK lseek
|                 ^~~~~
Source/ZLib/gzlib.c:252:9: note: in expansion of macro 'LSEEK'
252 |         LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
|         ^~~~~
make: *** [Makefile:61: Source/ZLib/gzlib.o] Error 1
make: *** Waiting for unfinished jobs....
Source/ZLib/gzread.c: In function 'gz_load':
Source/ZLib/gzread.c:35:15: error: implicit declaration of function 'read'; did you mean 'fread'? [-Wimplicit-function-declaration]
35 |         ret = read(state->fd, buf + *have, get);
|               ^~~~
|               fread …
```
> FreeImage: fix build with newer gcc 14

- python/python-pycairo/BUILD
- python/python-pycairo/DETAILS
which is needed by meld PR4954.
> python-pycairo: This needs to use meson so py3cairo.h gets installed

- devel/meld/BUILD
- devel/meld/DEPENDS
- devel/meld/DETAILS
Checking out https://github.com/lunar-linux/moonbase-other/pull/4954 and doing it locally, still wouldn't find the updated python-pycairo.
> meld: Bump to 3.22.2 and add python-pycairo depends.

- audio/tagparser/PRE_BUILD
Forgot to add PRE_BUILD in previous PR :P
> tagparser: build shared library instead of static

- libs/liburing/BUILD
- libs/liburing/DETAILS
I was getting HTTP error code 400, bad request, when using 'lget -w 2.8 liburing', so update the source URL to the repo hosted on Github.
> liburing: version bumped to 2.8

- web/links/BUILD
I was getting "C compiler cannot create executables" in configure... I found this in config.log:
configure:993: checking whether the C compiler (gcc  -O2 -march=x86-64 -fno-plt -fexceptions -pipe -fstack-clash-protection  -s -Wl,-z,relro,-z,now,--sort-common) works
configure:1009: gcc -o conftest  -O2 -march=x86-64 -fno-plt -fexceptions -pipe -fstack-clash-protection   -s -Wl,-z,relro,-z,now,--sort-common conftest.c  1>&5
configure:1006:1: error: return type defaults to 'int' [-Wimplicit-int]
> links: fix build with recent gcc 14

- virtual/qemu/patch.d/qemu-9.2.0-glibc-2.41.patch
The error I was getting was:
[...]
[2701/4634] Compiling C object libqemu-aarch64_be-linux-user.a.p/linux-user_syscall.c.o
FAILED: libqemu-aarch64_be-linux-user.a.p/linux-user_syscall.c.o 
gcc -m64 -Ilibqemu-aarch64_be-linux-user.a.p -I. -I.. -Itarget/arm -I../target/arm -I../common-user/host/x86_64 -I../linux-user/include/host/x86_64 -I../linux-user/include -Ilinux-user -I../linux-user -Ilinux-user/aarch64 -I../linux-user/aarch64 -Iqapi -Itrace -Iui -Iui/shader -I/usr/include/capstone -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -fdiagnostics-color=auto -Wall -Winvalid-pch -std=gnu11 -O2 -g -fstack-protector-strong -Wempty-body -Wendif-labels -Wexpansion-to-defined -Wformat-security -Wformat-y2k -Wignored-qualifiers -Wimplicit-fallthrough=2 -Winit-self …
> qemu: add Gentoo patch for glibc 2.41

- utils/rsyslog/BUILD
- utils/rsyslog/DEPENDS
- utils/rsyslog/PRE_BUILD
- utils/rsyslog/patch.d/rsyslog-8.2412.0-libgcrypt-config_not_found.patch
The error I had in configure was:
configure: error: libgcrypt-config not found in PATH
Which has been removed from recent libgcrypt.
> rsyslog: fix build with newer libgcrypt

- net/ntp/BUILD
The configure script was failing with:
configure: error: could not locate pthread_detach()
I found this in config.log:
```
configure:23116: checking for pthread_detach with <pthread.h>
configure:23139: gcc -o conftest  -O2 -march=x86-64 -fno-plt -fexceptions -pipe -fstack-clash-protection   -s -Wl,-z,relro,-z,now,--sort-common conftest.c    >&5
conftest.c: In function 'main':
conftest.c:166:16: error: passing argument 1 of 'pthread_detach' makes integer from pointer without a cast [-Wint-conversion]
166 | pthread_detach(NULL);
|                ^~~~
|                | 
|                void *
In file included from conftest.c:158:
/usr/include/pthread.h:269:38: note: expected 'pthread_t' {aka 'long unsigned int'} but argument is of type 'void *'
269 | extern int pthread_detach (pthread_t …
```
> ntp: fix build with newer gcc 14

- compilers/go-bootstrap/BUILD
- compilers/go-bootstrap/DETAILS
- compilers/go-bootstrap/POST_INSTALL
- compilers/go-bootstrap/PRE_BUILD
Ratler suggested we stop introducing additional bootstraps. With Go 1.24.0, a 4th one was needed. So use the minimum required prebuilt version instead.
> go-bootstrap: switch to prebuilt bootstrap (1.22.12)

- distributed/transmission/DEPENDS
- distributed/transmission/patch.d/transmission-4.0.6-miniupnpc-2.2.8.patch
The error I was getting was:
/usr/src/transmission-4.0.6/libtransmission/port-forwarding-upnp.cc:278:29: error: too few arguments to function 'int UPNP_GetValidIGD(UPNPDev*, UPNPUrls*, IGDdatas*, char*, int, char*, int)'
> transmission: add a Gentoo patch for newer miniupnpc

- libs/gdal/BUILD
- libs/gdal/DETAILS
The #include has been added upstream, so remove the fix.
> gdal: version bumped to 3.10.2

- wayland/xwayland/DETAILS
Just like xorg-server, this release fixes [CVE-2025-49176](https://www.cvedetails.com/cve/CVE-2025-49176) (See https://lists.x.org/archives/xorg/2025-June/062055.html)
> xwayland: version bumped to 24.1.8 + CVE fix

- x11-wm/fluxbox-git/DETAILS
No more auto_ptr C++ warnings! (The output was filled with those before.)
> fluxbox-git: bumped to the latest commit

- x11-utils/gkrellm/BUILD
- x11-utils/gkrellm/patch.d/gkrellm-2.3.11-linux_6.16.2_fix.patch
So starting with linux 6.16.1, gkrellm doesn't show networking usage anymore. Some Gentoo user said it was because rewind() was now returning ESPIPE as error.
The fix consists of reopening and reclosing the metrics /proc files on every call instead of using rewind().
> gkrellm: add a patch to restore network monitoring with linux 6.16.1-3
