lunar-linux/moonbase-other

- web/flash-plugin-11/BUILD
- web/flash-plugin-11/DETAILS
- web/flash-plugin-11/DETAILS.x86_64
> flash-plugin-11: version bumped to 11.2.202.442

- python/Python-3/DETAILS
See http://bugs.gw.com/view.php?id=433 for details
> Python-3: use tgz until file fixes their misidentification

- filesys/zfs/DETAILS
See:
http://list.zfsonlinux.org/pipermail/zfs-announce/2015-April/000001.html
for the full announcement.
> zfs: version bump to 0.6.4

- shells/zsh/BUILD
- shells/zsh/CONFIGURE
- shells/zsh/DEPENDS
- shells/zsh/DETAILS
- shells/zsh/PRE_BUILD
> zsh: version bumped to 5.1.1.

- filesys/zfs-utils/BUILD
- filesys/zfs-utils/DETAILS
- filesys/zfs/BUILD
- filesys/zfs/DETAILS
- kernel/spl/BUILD
- kernel/spl/DETAILS
This PR take a few changes from #510 and thus closes #510.
> spl and zfs version bumped

- devel/udisks/BUILD
- devel/udisks/DEPENDS
- devel/udisks/DETAILS
- devel/udisks/PRE_BUILD
> udisks: version bump + fix BUILD

- utils/augeas/DETAILS
I've been playing with this for a couple of days, it seems like it could come in handy if you have lots of hosts to manage.
From the web site:
Augeas is a configuration editing tool. It parses configuration
files in their native formats and transforms them into a tree.
Configuration changes are made by manipulating this tree and saving
it back into native config files.
> augeas: new module, a configuration editing tool

- cd/cdrtools/DETAILS
mkisofs now includes DVD-Audio support.
> cdrtools: version bumped to 3.02a04

- shells/busybox/BUILD
- shells/busybox/CONFIGURE
Someone's going to have to try this out manually, I don't think jenkins can try out multiple options.
> Busybox: Add option to build as a static executable.

- compilers/llvm/BUILD
- compilers/llvm/CONFIGURE
- compilers/llvm/DEPENDS
- compilers/llvm/DETAILS
- compilers/llvm/PRE_BUILD
This is based on florin's bump
> llvm: version bump & cmake build

- java/sun-jdk/BUILD
- java/sun-jdk/DEPENDS
- java/sun-jdk/DETAILS.x86_64
- java/sun-jdk/POST_REMOVE
- java/sun-jdk/PRE_BUILD
- java/sun-jdk/sun_jconsole.desktop
- java/sun-jdk/sun_jmc.desktop
- java/sun-jdk/sun_jvisualvm.desktop
- java/sun-jdk/sun_policytool.desktop
reworked the module and bumped to the last version.
> sun-jdk: version bumped to 8u74.

- zbeta/libressl/DEPENDS
- zbeta/libressl/DETAILS
- zbeta/libressl/POST_BUILD
- zbeta/libressl/POST_INSTALL
This is very much try-at-your-own-risk material at this point.  It
compiles smoothly and works well on my system, and all functionality
appears to be present and stable, but it does replace a pretty central
component.
> libressl: Replacement for OpenSSL, by the OpenBSD team.

- video/ffmpeg/BUILD
- video/ffmpeg/CONFIGURE
- video/ffmpeg/DEPENDS
- video/ffmpeg/DETAILS
Some modules in the moonbase could not support the new API. for some of them there are patches for that.
> ffmpeg: version bumped to 3.0.1.

- net/samba/BUILD
- net/samba/CONFIGURE
- net/samba/DEPENDS
- net/samba/DETAILS
This changes the build a bit, and the configuration flags, but now it
supports being an Active Directory controller, which is pretty neat.
Pull request because this is a really big version bump.
> samba: Version up to 4.4.2.

- devel/jenkins/DETAILS
> jenkins: version bumped to 2.1.

- web/chromium/BUILD
- web/chromium/DEPENDS
- web/chromium/DETAILS
- web/chromium/PRE_BUILD
- system ffmpeg is no longer a working option, revert to using bundled version.
- removed optimization fixes, doesn't seem to be necessary anymore
- revert to bundled icu4c version
- other cleanups
> chromium: version bumped to 50.0.2661.102

- games/openttd/DETAILS
version from 1.3.3 to 1.6.0. Also updated opengfx from 0.4.7 to 0.5.2
> openttd latest version update

- games/openttd/DETAILS
Hoping to never forget this again ^^
> corrected a forgotten 'UPDATED' field in DETAILS

- utils/gamin/BUILD
- utils/gamin/DETAILS
potential kde application issues  not starting, experienced that in a
small way myself and other just to clean up the BUILD
> gamin: adding a couple of patches from arch linux, one to deal with

- x11-utils/compton-conf/BUILD
- x11-utils/compton-conf/DEPENDS
- x11-utils/compton-conf/DETAILS
- x11-utils/compton-conf/PRE_BUILD
An attempt to port it to Qt 5.x.
> compton-conf: a Qt GUI for compton.

- audio/pulseaudio/DEPENDS
Fixed broken configure from '--with=database=tdb' to '--with-database=tdb'
> Corrected a typo in pulseaudio DEPENDS

- compilers/erlang/DETAILS
> erlang: version bump

- editors/emacs/BUILD
- editors/emacs/DEPENDS
- editors/emacs/DETAILS
- editors/emacs/PRE_BUILD
Bring more improvements to the default module.
> emacs: version bumped to 25.1.

- web/flash-plugin-11/DETAILS
- web/flash-plugin-11/DETAILS.x86_64
Some websites are starting to warn about the vulnerability of the current version.
> flash-plugin-11: version bumped to 11.2.202.635

- graphics/gtk+-3/DETAILS
It depends on glib-2 version 2.50.1 (there's a PR for it on core)
> gtk+-3: version bumped to 3.22.1.

- utils/duc/DETAILS
- utils/duc/POST_REMOVE
Fixed miswritten POST_REMOVE commands
> duc: version bumped to 1.4.1 + POST_REMOVE corr.

- games/angband/BUILD
- games/angband/DEPENDS
- games/angband/DETAILS
- games/angband/POST_INSTALL
- games/angband/POST_REMOVE
- games/angband/PRE_BUILD
fixed the missing directories and wrong group in /var/games/angband which were making the game to fail to start
> angband: version bumped to 4.0.5 + changed (un)install

- libs/eigen3/DETAILS
After THREE YEARS! they finally managed to release.
Ubuntu distributed the beta for quite some time already...
> eigen3: major version bump

- utils/duc/DETAILS
- utils/duc/PRE_BUILD
My tiny patch has been merged into the new release.
> duc: version bumped to 1.4.2

- virtual/VirtualBox/BUILD
- virtual/VirtualBox/DEPENDS
- virtual/VirtualBox/DETAILS
works without problems for my setup
> VirtualBox: major version bump

- games/xbill/BUILD
- games/xbill/DEPENDS
- games/xbill/DETAILS
Heard from the IRC ##linux community
> New module: xbill 2.1, arcade-like game

- x11-wm/i3/BUILD
- x11-wm/i3/DEPENDS
- x11-wm/i3/DETAILS
The old objects I am not sure whether it's caused by docker, I open it anyway.
> i3: bump to 4.13 again

- web/chromium/BUILD
- web/chromium/DEPENDS
- web/chromium/DETAILS
- web/chromium/PRE_BUILD
- Major refactoring
- added patches for glibc, widevine and ffmpeg
> chromium: version bumped to 56.0.2924.87

- devel/rlwrap/DETAILS
Also, changed the URL: the project seems to have moved to github.
> rlwrap: Version bump to 0.43.

- compilers/Cython/DETAILS
> Change the Hash value

- ftp/curl/DETAILS
curl:Update download URL
http method can not download the software.
> curl:Update download URL

- net/dhcp/DETAILS
> dhcp:add Download URL

- graphics/graphviz/DETAILS
graphviz:Add an available download link.
From:[https://graphviz.gitlab.io/_pages/Download/Download_source.html](url)
> graphviz:Add an available download link.

- compilers/vala/DEPENDS
> vala:Add a dependency

- archive/libzip/DETAILS
libzip: version bumped to 1.3.2
> libzip: version bumped to 1.3.2

- libs/ilmbase/DETAILS
> ilmbase:bump to 2.2.1

- libs/openexr/DETAILS
> openexr:bump to 2.2.1

- video/x265/DETAILS
Add an available download link
> Add an available download link

- zbeta/x264-snapshot/DETAILS
x264-snapshot:version bumped to 20171206-2245
> x264-snapshot:version bumped to 20171206-2245

- utils/lm_sensors/DETAILS
> lm_sensors:Add a download URL

- filesys/zfs-utils/BUILD
- filesys/zfs-utils/DETAILS
- filesys/zfs-utils/PRE_BUILD
- web/lighttpd/DETAILS
This fixes a couple of issues with dracut's zfs module.  One is a problem on our end (well, not a problem, just a thing we do differently), I think, and another is a problem on the ZFS end.
> Zfs utils dracut fixes

- crypto/gnupg2/DETAILS
> gnupg2:Add a download URL 

- web/node/DETAILS
> node:update download URL

- mail/dovecot/DETAILS
Didn't this go through CI or anything?
> dovecot: fix build.

- filemanagers/lfm/DEPENDS
It needs setuptools-3 at runtime.
> lfm: it needs setuptools-3 at runtime.

- i18n/icu4c/DETAILS
This will trigger at 'lunar fix' a lot of rebuilds in the system.
Treat it with carefull!
> icu4c: version bumped to 61.1.

- compilers/ruby/DETAILS
> ruby:Change download URL

- audio/libsndfile/DETAILS
libsndfile:Update download URL
> libsndfile:Update download URL

- net/obex-data-server/DETAILS
> obex-data-server:Update download URL

- devel/cmake/DETAILS
> cmake:Add download URL

- compilers/rustc/DETAILS
> rustc:Update download URL

- libs/pcre2/DETAILS
> pcre2:Add download URL

- i18n/iso-codes/DETAILS
> iso-codes:Update DETAILS

- compilers/rustc/DETAILS.x86_64
rustc:update download URL to https
> rustc:update download URL to https

- graphics/blender/DETAILS
> blender:Bump to 2.79b

- bluetooth/bluez-5/DETAILS
> bluez-5:fix hashs

- i18n/unicode-character-database/DEPENDS
unicode-character-database:"bsdtar" in BUILD file needs libarchive.
> unicode-character-database:Add a depends

- audio/gst-plugins-base-1.0/DEPENDS
gst-plugins-base-1.0:fix a typo
> gst-plugins-base-1.0:fix a typo

- libs/libpipeline/DETAILS
libpipeline:Change download URL to https
> libpipeline:Change download URL to https

- libs/libunwind/DETAILS
libunwind:Change download URL to https
> libunwind:Change download URL to https

- doc-tools/docbook-xsl/DETAILS
docbook-xsl:Change download URL to https
> docbook-xsl:Change download URL to https

- libs/ndctl/DETAILS
> ndctl:version bumped to 62

- i18n/unicode-character-database/DETAILS
unicode-character-database:fix hash
> unicode-character-database:fix hash

- crypto/libssh/DETAILS
> libssh:fix hash

- net/bind/DETAILS
Seriously, how did this happen though?
> bind: Removed stray line feed in DETAILS file

- graphics/inkscape/DETAILS
- graphics/inkscape/patch.d/noconst.patch
- graphics/inkscape/patch.d/poppler-0.65.0.patch
Credit goes to Arch Linux for the patches.
> inkscape: Add patch.d and patches to fix the build

- python/pyatspi/DETAILS
> pyatspi:bumped to 2.29.90

- libs/nss/DETAILS
nss:Change download URL to https
> nss:Change download URL to https

- crypto/cyrus-sasl/DETAILS
cyrus-sasl:Change download URL to https
> cyrus-sasl:Change download URL to https

- crater/jfsutils/BUILD
- crater/jfsutils/DEPENDS
- crater/jfsutils/DETAILS
- crater/jfsutils/PRE_BUILD
It doesn't build with the latest version of glibc and I couldn't be
bothered mkaing the effort.  It's unmaintained and forgotten.
> jfsutils: It's moving to the crater.

- libs/qrencode/DETAILS
qrencode:Change download URL to https
> qrencode:Change download URL to https

- net/ntp/DETAILS
> ntp: version bumped to 4.2.8p12.

- video/v4l-utils/DETAILS
v4l-utils:Change download URL to https
> v4l-utils:Change download URL to https

- devel/xapian-core/DETAILS
xapian-core:Change download URL to https and add web site.
> xapian-core:Change download URL to https

- graphics/openexr/DEPENDS
> openexr:Add a depends

- devel/autoconf-mozilla/DETAILS
autoconf-mozilla:Add a download URL
> autoconf-mozilla:Add a download URL

- filesys/jfsutils/BUILD
- filesys/jfsutils/DEPENDS
- filesys/jfsutils/DETAILS
- filesys/jfsutils/PRE_BUILD
- filesys/ntfs-3g/BUILD
- filesys/ntfs-3g/CONFIGURE
- filesys/ntfs-3g/DEPENDS
- filesys/ntfs-3g/DETAILS
- filesys/ntfs-3g/PRE_BUILD
Time to clean up some clutter in moonbase-core: move jfs and ntfs to moonbase-other where they beling.
> Move nonessential filesystems

- graphics/libwebp/DETAILS
> libwebp:add a download URL

- devel/polkit/DETAILS
> polkit:use to https

- app-themes/hicolor-icon-theme/DETAILS
hicolor-icon-theme:use to https
> hicolor-icon-theme:use to https

- libs/orc/DETAILS
> orc:use to https

- graphics/harfbuzz/DETAILS
> harfbuzz:use to https

- x11-utils/startup-notification/DETAILS
startup-notification:use to https
> startup-notification:use to https

- devel/desktop-file-utils/DETAILS
desktop-file-utils:use to https
> desktop-file-utils:use to https

- utils/media-player-info/DETAILS
media-player-info:use to https
> media-player-info:use to https

- libs/libspectre/DETAILS
> libspectre:use to https

- virtual/virglrenderer/DETAILS
> virglrenderer:use to https

- audio/gst-ffmpeg/DETAILS
> gst-ffmpeg:use to https

- net/geoip-database/DETAILS
> geoip-database:fix hash

- net/openldap/DETAILS
> openldap:add a download URL

- devel/udisks2/DETAILS
- virtual/virglrenderer/DETAILS
> udisks2:use to https

- chat/farstream/DETAILS
> farstream:use to https

- graphics/colord/DETAILS
> colord:use to https

- libs/boost/DETAILS
> boost:add a download URL

- libs/libxslt/DETAILS
libxslt:add a download URL and fix a typo.
> libxslt:add a download URL and fix a typo.

- doc-tools/sgml-common/DETAILS
sgml-common:update download url
> sgml-common:update download url

- archive/tar-static/DETAILS
> tar-static:change to https

- games/freedink-data/DETAILS
> freedink-data:change to https

- devel/cvs/DETAILS
> cvs:change to https

- libs/libunistring/DETAILS
> libunistring:change to https

- crypto/libtasn1/DETAILS
> libtasn1:change download URL

- audio/alsa-lib/DETAILS
> alsa-lib:add a download URL

- devel/polkit/BUILD
- devel/polkit/DEPENDS
i hope that this will prevent xsltproc error on jenkins
> polkit: disable documentation buildind

- devel/source-highlight/DETAILS
source-highlight:change to https
> source-highlight:change to https

- devel/subversion/BUILD
- devel/subversion/DETAILS
- devel/subversion/patch.d/apr-1.7.0-support.patch
Also add in a patch that fixes building with APR 1.7.0.
> subversion: Bump to version 1.12.0.

- utils/chrono/DEPENDS
- utils/chrono/DETAILS
-Fixed issue #3 about the countdown not repeating correctly
-Added few tests
> chrono: version bumped to 0.2.34

- wayland/wayland/DETAILS
> wayland:Change to https

- devel/scons/BUILD
> scons:fix a tpyo in BUILD

- utils/chrono/DETAILS
> chrono: version bumped to 0.2.39

- libs/libbytesize/DEPENDS
>  libbytesize:add a depends

- libs/libcap-ng/DETAILS
> libcap-ng:Change to https

- utils/chrono/DETAILS
I found out 0.2.39 wasn't counting days
> chrono: version bumped to 0.2.40

- shells/fish/DETAILS
Finally, a command line for the 90s.
> fish: A simple and friendly shell.@

- i18n/ibus/BUILD
- i18n/ibus/CONFIGURE
> ibus: add CONFIGURE in order to install or not the gschemas files

- i18n/iso-codes/DETAILS
> iso-codes:change to https

- graphics/SDL/DETAILS
SDL:Change download URL to https
> SDL:Change download URL to https

- audio/gst-plugins-good/BUILD
gst-plugins-good:fix BUILD file
>  gst-plugins-good:fix BUILD file

- archive/dpkg/DETAILS
> dpkg:Bump to 1.19.7

- devel/re2/DETAILS
> re2:fix hash

- zbeta/chromium-arch/DETAILS.x86_64
> chromium-arch:fix hash

- python/python2-markupsafe/DEPENDS
python2-markupsafe:fix depends type
> python2-markupsafe:fix depends type

- net/ntp/DETAILS
> ntp:fix hash

- libs/fftw3/DETAILS
> fftw3:Bump to 3.3.8

- devel/polkit/DEPENDS
depends-on:https://github.com/lunar-linux/moonbase-other/pull/1420
> polkit: use mozjs60, latest mozjs68 is not yet supported

- science/octave/DETAILS
> octave:Bump to 5.2.0

- distributed/openmp/DETAILS
> openmp: version bump

- graphics/freeglut/DEPENDS
> freeglut :add dependency

- graphics/gimp/DETAILS
Version bump to 2.10.18, update sha256sum
> GIMP: version bump

- devel/cbindgen/DETAILS
bump to version 0.14.1, update sha256sum
> cbindgen: version bump

- web/firefox-bin/DETAILS
- web/firefox-bin/DETAILS.x86_64
DEPENDS and DEPENDS.X86_64:
- Update version, sha256, and modification date.
> firefox-bin: version bump

- utils/bashtop/DETAILS
> bashtop:up to 0.8.25

- libs/libytnef/BUILD
- libs/libytnef/DETAILS
BUILD: added an line to invoke autogen.sh.
DETAILS: version bump, and updated the URL (developer has moved to github).
> libytnef: version-bump, update URL

- mail/birdtray/BUILD
- mail/birdtray/DEPENDS
- mail/birdtray/DETAILS
Birdtray is a system tray new mail notification for Thunderbird
> birdtray: systemtray email monitor for Thunderbird

- graphics/scour/BUILD
- graphics/scour/DEPENDS
- graphics/scour/DETAILS
Scour is a commandline SVG optimizer.
BUILD: scour doesn't have a ./configure file, this skips straight to default_make.
The rest is standard module
> scour: SVG Optimizer

- graphics/inkscape/DETAILS
Updated DETAILS to newest version
> inkscape - version bump to 1.0.1

- graphics/Argyll/BUILD
- graphics/Argyll/DETAILS
- graphics/Argyll/patch.d/argyllcms-2.1.2-fno-common.patch
- Updated DETAILS to newest version, 
- Added patchfile to work with GCC 10
> Argyll - version bump, gcc 10 fix

- compilers/ocaml/DETAILS
Version bump - update also gives GCC 10 compatability.
> ocaml - version bump, fixes GCC 10.

- graphics/dcraw/BUILD
- graphics/dcraw/DEPENDS
- graphics/dcraw/DETAILS
Original website no longer works,  switched to author's own site.
> dcraw - update dl location

- crypto/gnupg/DETAILS
- devel/cmake/DETAILS
cmake: fix UPDATED field
gnupg: fix UPDATED field
> fix UPDATED field in cmake and gnupg

- graphics/gmic/BUILD
- graphics/gmic/DEPENDS
- graphics/gmic/DETAILS
This is just the libraries and CLI. If/when this is merged, I'll add _gmic-qt,_ which contains the GUIs.
> gmic - image processing framework

- graphics/libraqm/BUILD
- graphics/libraqm/DEPENDS
- graphics/libraqm/DETAILS
new module!
The raqm libraries are supported in ImageMagick and libgd (I'll update those if this is merged).
> libraqm - library and API for text layout

- graphics/gmic-qt/BUILD
- graphics/gmic-qt/DEPENDS
- graphics/gmic-qt/DETAILS
As mentioned with the combined gmic - gmic-qt PR from several days ago, this was separated to isolate the build fail with gmic-qt.
- I'm expecting this to fail like the previous times.
- It appears to be a Jenkins failure when building QT5, and not directly this module.
> gmic-qt - 2nd try

- sql/mariadb/DETAILS
- sql/mariadb/PRE_BUILD
PRE_BUILD: removed unneeded line (causes compile fail on this version)
DETAILS: normal version bump items
> Mariadb - version bump

- doc-tools/docutils/DETAILS
> docutils:up to 0.17.1

- libs/boost/DETAILS
boost:Change Download URL to available
> boost:Change Download URL to available

- doc-tools/atril/DETAILS
bump from 1.25 to 1.25.1 - minor bug fixes
> atril - version bump

- systemd.d/syslog-ng.service
The service file was packaged with the source.
> syslog-ng: add systemd service

- utils/syslog-ng/systemd.d/syslog-ng.service
Review of https://github.com/lunar-linux/moonbase-other/pull/1593
> syslog-ng: Apply Ratler's comments

- graphics/inkscape/BUILD
- graphics/inkscape/DEPENDS
- graphics/inkscape/DETAILS
BUILD - GraphicsMagick works now, NLS is automatic
DEPENDS - updated some dependencies, added some new _optionals_
DETAILS - normal version bump changes
> inkscape - version bump

- libs/pcre2/DETAILS
> pcre2:up to 10.39

- graphics/gmic-qt/DETAILS
Forgot about this! Goes with the gmic push from a couple days ago.
DETAILS - standard version bump changes
> gmic-qt - version bump

- doc-tools/atril/DETAILS
> atril version bump

- web/woff2/DEPENDS
- web/woff2/DETAILS
New module, support for compressed online fonts.
> woff2 - web open font format

- graphics/libavif/DEPENDS
- graphics/libavif/DETAILS
New module, part of the AV1 OpenMedia family : https://aomedia.org/
> LibAVIF - avif image support

- libs/libhandy/DETAILS
normal updates to DETAILS for a version bump
> libhandy version bump

- libs/spdlog/DETAILS
> spdlog: version bump

- web/firefox/BUILD
- web/firefox/DEPENDS
- web/firefox/DETAILS
- web/firefox/PRE_BUILD
- web/firefox/google_api_key
- web/firefox/mozconfig
Reverts lunar-linux/moonbase-other#1634
This PR is not complete yet. We just had a discussion about things that needs to be fixed before merging.
> Revert "firefox: version bump and lots of other fixes"

- libs/fftw/BUILD
fftw:add --disable-fortran in BUILD
> fftw:add --disable-fortran in BUILD

- graphics/harfbuzz/DETAILS
> harfbuzz:fix UPDATED

- audio/fdk-aac/DETAILS
> fdk-aac:Bump to 2.0.2

- audio/mpc/DETAILS
> mpc:bump to 0.34

- audio/wavpack/DETAILS
> wavpack:bump to 5.4.0

- audio/abcde/DETAILS
> abcde:bumped to 2.9.3

- archive/zopfli/DETAILS
> zopfli:Bump to 1.0.3

- audio/paprefs/DETAILS
> paprefs:bump to 1.2

- audio/tagparser/DEPENDS
- audio/tagparser/DETAILS
> tagparser:bump to 11.0.0

- audio/chromaprint/DETAILS
> chromaprint:bumped to 1.5.1

- graphics/djvulibre/DETAILS
djvulibre:set SOURCE_DIRECTORY
> djvulibre:set SOURCE_DIRECTORY

- compilers/php/DETAILS
https://www.php.net/ChangeLog-8.php#8.2.0
> php: version bumped to 8.2.0

- filesys/zfs-utils/DETAILS
- filesys/zfs/DETAILS
Now including support for Linux 6.0!
> zfs, zfs-utils: Version bumped to 2.1.7

- compilers/php/DETAILS
https://www.php.net/ChangeLog-8.php#8.2.1
> php: version bumped to 8.2.1

- utils/rsyslog/DEPENDS
- utils/rsyslog/DETAILS
Corrected a typo and removed a duplicate optional_depends block.
> rsyslog: version bumped to 8.2212.0

- virtual/qemu/BUILD
- virtual/qemu/CONFIGURE
- virtual/qemu/DEPENDS
- virtual/qemu/DETAILS
Changed a bunch of things because qemu's switched its build system to ninja. Fortunately the devs helpfully still included a "configure" script that writes a makefile so I didn't have to make quite such dramatic changes as I'd initially feared.
> qemu: Bumped to 7.2.0

- filesys/xorriso/DETAILS
How this wasn't in the moonbase already is a wonder to me. It's so very useful!
> New module: xorriso: an ISO9660/RockRidge filesystem manipulator

- graphics/ImageMagick/DETAILS
Version 7.1.0-62 does not exist
> ImageMagick:bump to 7.1.1-8

- graphics/ImageMagick/DETAILS
ImageMagick:bump to 7.1.1-12 and fix the download link,otherwise the original link will not be available when the new version appears.
> ImageMagick:bump to 7.1.1-12

- devel/ocaml-saturn/BUILD
- devel/ocaml-saturn/DEPENDS
- devel/ocaml-saturn/DETAILS
- devel/ocaml-saturn/PRE_BUILD
- devel/ocaml-saturn/remove-domain-shims-dep.diff
needed just to compile the ocaml related modules that were in our repository before.
> ocaml-saturn: Adding. Just another depends for the myriad of modules

- crater/heirloom-mailx/BUILD
- crater/heirloom-mailx/CONFLICTS
- crater/heirloom-mailx/DETAILS
- crater/heirloom-mailx/PRE_BUILD
You've served us well, now your source code has gone missing. Now you can live in the crater for our historical records.
> heirloom-mailx: has fallen into the crater

- utils/chrono/BUILD
- utils/chrono/DETAILS
> chrono: version bumped to 0.2.45

- compilers/php/DETAILS
https://www.php.net/ChangeLog-8.php#8.2.10
> php: version bumped to 8.2.10

- python/python-bson/DEPENDS
- python/python-bson/DETAILS
MongoDB depends on this. See https://github.com/lunar-linux/moonbase-other/pull/2131
> python-bson: new module

- wayland/xwayland/DETAILS
It'll probably tank due to mesa/llvm/something else.
> xwayland: Bump to 23.2.1.

- devel/rebar3/BUILD
- devel/rebar3/DEPENDS
- devel/rebar3/DETAILS
> rebar3: Adding. Current moonbase rebar-2.x is depreciated, and

- audio/gstreamer/BUILD
- audio/gstreamer/DEPENDS
> gstreamer: Disabling docs and gobject-instrospetion may as well

- virtual/VirtualBox/BUILD
- virtual/VirtualBox/DEPENDS
- virtual/VirtualBox/DETAILS
- virtual/VirtualBox/LocalConfig.kmk
if bumping this you *should* also check/bump virtual_module as they are one and the same tarballs.
> VirtualBox: Bump to 7.0.12. Adding optional_dpeends gsoap. Also,

- wayland/egl-wayland/BUILD
- wayland/egl-wayland/DEPENDS
- wayland/egl-wayland/DETAILS
- wayland/egl-wayland/patch.d/egl-wayland-1.1.6-remove-werror.patch
> egl-wayland: Bump to 1.1.13 and adding a remove werror patch from

- python/python-pythran/BUILD
- python/python-pythran/DEPENDS
- python/python-pythran/DETAILS
those depends are really needed.
> python-pythran: Bump to 0.12.0. Also testing DEPENDS to see if

- web/owncloudclient/BUILD
- web/owncloudclient/DEPENDS
- web/owncloudclient/DETAILS
adjustments to BUILD and DEPENDS.
> owncloudclient: Bump to 5.2.0.12726. It now depends on qt6. Making

- utils/autoenv/DETAILS
The old URL redirects to the new one.
> autoenv: update URLs from redirect

- video/dav1d/DETAILS
- video/dav1d/POST_INSTALL
lunar fix modules that use it if installed.
> dav1d: Bump to 1.4.0 and adding a POST_INSTALL to

- python/python-tomli/BUILD
- python/python-tomli/POST_INSTALL
> python-tomli: Change build process, prior was installing

- net/libnfs/BUILD
- net/libnfs/DETAILS
> libnfs: Switching to cmake build as some modules look for

- python/astropy/BUILD
- python/astropy/DEPENDS
- python/astropy/DETAILS
https://pypi.org/project/pyfits/.
> astropy: Adding. Replaces python-pyfits per;

- compilers/go-bootstrap3/BUILD
- compilers/go-bootstrap3/CONFIGURE
- compilers/go-bootstrap3/DEPENDS
- compilers/go-bootstrap3/DETAILS
- compilers/go-bootstrap3/POST_INSTALL
- compilers/go-bootstrap3/PRE_BUILD
Compiling from scratch seems to be an incredibly low priority for the Go development team.
> go: Add yet another level of bootstraps

- crater/README
The creation of this file is mostly justified to keep the directory present even if there's no modules in it. And it doesn't hurt to add a little description to it :)
> other/crater: add a basic README

- graphics/gtk+-2/BUILD
The error message that I was getting was:
/var/lib/lunar/moonbase-git/zlocal/gtk+-2/BUILD: line 24: ./autogen.sh: No such file or directory
> gtk+-2: fix broken BUILD

- games/toppler/BUILD
- games/toppler/DEPENDS
- games/toppler/DETAILS
- games/toppler/PRE_BUILD
> toppler: Bump to 1.3. Requires ImageMagick for its convert app and

- libs/boost/DETAILS
- libs/boost/POST_INSTALL
fixes if some of the lower level modules are installed affected by boost bumps. Hopefully makes this a little less painful overall.
> boost: Bump to 1.85.0 and adjusting POST_INSTALL to add some lunar

- crypto/steghide/BUILD
- crypto/steghide/DETAILS
- crypto/steghide/PRE_BUILD
- crypto/steghide/patch.d/001-buildsystem.patch
- crypto/steghide/patch.d/002-include-climits.patch
- crypto/steghide/patch.d/003-add-hardening.patch
- crypto/steghide/patch.d/004-fix-spelling.patch
- crypto/steghide/patch.d/005-consolidated-gcc-patches.patch
> steghide: Needed a freshing up. Adding some patches from the

- utils/zxing-cpp/BUILD
- utils/zxing-cpp/DETAILS
The new URL is taken from a redirect.
> zxing-cpp: version bumped to 2.2.1

- python/python-pypng/BUILD
- python/python-pypng/DEPENDS
- python/python-pypng/DETAILS
module called python-qrcode which will be a depends for a future bump of gajim.
> python-pypng: Adding, will be a depends for another new python

- archive/zip/BUILD
- archive/zip/DETAILS
Note that it still requires patching to work with gcc 14.
> zip: Move from core to other

- printer/libcupsfilters/BUILD
- printer/libcupsfilters/DEPENDS
- printer/libcupsfilters/DETAILS
> libcupsfilters: Adding. Will be depends for libppd which will be a

- graphics/colord/DEPENDS
- graphics/colord/DETAILS
- graphics/colord/PRE_BUILD
PRE_BUILD adjusting its service file.
> colord: A few changes to DEPENDS and PRE_BUILD. Primarily in

- python/wxPython/BUILD
- python/wxPython/DEPENDS
- python/wxPython/DETAILS
- python/wxPython/patch.d/wxpython-4.2.0-cython-3.patch
- python/wxPython/patch.d/wxpython-4.2.0-flags.patch
- python/wxPython/patch.d/wxpython-4.2.0-no-webkit.patch
- python/wxPython/patch.d/wxpython-4.2.1-doxygen-1.9.7.patch
- python/wxPython/patch.d/wxpython-4.2.1-integer-division-for-randint.patch
- python/wxPython/patch.d/wxpython-4.2.1-x86-time.patch
> wxPython: Moving out of crater, bump to 4.2.1 and adding some

- libs/libnvme/DETAILS
Next will come nvme-cli, it just needs the CI to have this merged first otherwise it will fail with libnvme 1.8
> libnvme: version bumped to 1.10

- doc-tools/xmlto/patch.d/xmlto-0.0.28-fix-warnings.patch
As per the CI failure seen from https://github.com/lunar-linux/moonbase-other/pull/4319
> xmlto: fix build with gcc 14 (Gentoo patch)

- compilers/php/DEPENDS
- compilers/php/DETAILS
> php: version bumped to 8.3.11

- kernel/Vulkan-Headers/BUILD
- kernel/Vulkan-Headers/DEPENDS
- kernel/Vulkan-Headers/DETAILS
> Vulkan-Headers: Bump to 1.3.295 and adding a BUILD to use Ninja

- web/node/BUILD
- web/node/DEPENDS
- web/node/DETAILS
The zlib option is already specified into OPTS in BUILD.
> node: version bumped to 23.3.0

- web/w3m/DEPENDS
See the discussion at https://bugs.gentoo.org/753917
> w3m: try a CI fix

- utils/dd_rescue/BUILD
- utils/dd_rescue/DETAILS
The configuration was running twice...
> dd_rescue: version bumped to 1.99.18

- ftp/lftp/DETAILS
> update lftp to v4.9.3

- system/hwdata/DETAILS
- system/hwdata/PRE_BUILD
Move the .pc file from /usr/share/pkgconfig to /usr/lib/pkgconfig.
> hwdata: version bumped to 0.392

- python/python-numpy/DETAILS
The first bump in Year of Yi Si（乙巳年）.
Happy new year and Good luck~!
> python-numpy:bump to 2.2.2

- libs/libxml2/DETAILS
> bump libxml2 to 2.13.5

- ftp/ncftp/DETAILS
- ftp/ncftp/PRE_BUILD
> Ncftp 3.2.7

- ftp/axel/BUILD
- ftp/axel/DEPENDS
- ftp/axel/DETAILS
Add module for axel download accelerator v2.17.14
> New module: Axel 2.17.14

- doc-tools/simdutf/DETAILS
node 24.3.0 builds fine with this.
> simdutf: version bumped to 7.3.2

- net/haproxy/BUILD
- net/haproxy/DEPENDS
- net/haproxy/DETAILS
It's a fast, reliable load balancer
It could probably do with a systemd unit file but the package maintainers haven't seen fit to include one so I'll make one eventually
> haproxy: New module
